spring:
  datasource:
    username: zhxt_dba
    password: oracle
    url: jdbc:oracle:thin:@192.168.11.130:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 2000
